{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jx-cdevents-adapter.serviceAccountName" . }}
  labels:
    {{- include "jx-cdevents-adapter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "jx-cdevents-adapter.serviceAccountName" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - providers
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "jx-cdevents-adapter.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "jx-cdevents-adapter.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "jx-cdevents-adapter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "jx-cdevents-adapter.serviceAccountName" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - providers
    verbs:
      - get
      - update
      - create
      - list
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "jx-cdevents-adapter.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "jx-cdevents-adapter.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "jx-cdevents-adapter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
